### ISSUE TITLE
Looking for simple, less generic examples

### ISSUE THREAD

**Issue by keithmgould** [caffe2/BlueWhale#13]
Hey Guys,

Thank you again for this repo. The issue I'm having is that its a bit much regarding learning how to use Caffe2 for RL. For comparison, [this](https://github.com/pytorch/examples/blob/master/reinforcement_learning/reinforce.py) simple script is pretty helpful to see how to solve cart-pole with PyTorch. 

Conceptually, I'm still pretty confused about how to do RL in Caffe2, and its a bit much to get through all of the code in BlueWhale.  Maybe a blog post would be better than this repo for the type of example I'm looking for. But I can't find that anywhere. Have you guys seen anything, or do you have anything stashed away that might work? Even as a gist?

For what its worth the part that I'm stuck on is: It seems when you run the model, it goes through all operations (forward pass and then backward pass), but I don't want the backward pass until the episode is complete.

I got started on what I'm asking for above, its [here](https://github.com/keithmgould/caffe2_cartpole_reinforce) but it only goes up to the forward pass, as I'm not sure how to work with Caffe2 to handle waiting until episode is complete for backward pass.

Thank you again!!

**Comment by MisterTea** [comment]
Hey Keith!  Check out our openai gym test for more details: https://github.com/caffe2/BlueWhale/tree/master/ml/rl/test/gym

**Comment by keithmgould** [comment]
Thank you Jason! 

Will close this issue.
